
version: '3.8'

services:
  db:
    image: postgres:15
    container_name: inventario_db
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - inventario_net
    restart: unless-stopped

  web:
    build: .
    container_name: inventario_web
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - inventario_net
    restart: unless-stopped
    # ports solo si quieres probar directamente sin Nginx
    # ports:
    #   - "5000:5000"

  nginx:
    image: nginx:alpine
    container_name: inventario_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web
    networks:
      - inventario_net
    restart: unless-stopped

volumes:
  pgdata:

networks:
  inventario_net:
